# Generated by Django 4.1 on 2022-12-31 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='admin',
        ),
    ]
