# Generated by Django 4.1 on 2023-01-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_addcourse_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='meg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=40)),
            ],
        ),
    ]
