# Generated by Django 4.1 on 2023-01-01 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_meg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='meg',
        ),
    ]
