# Generated by Django 4.1 on 2023-01-01 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addsub',
            old_name='cC',
            new_name='courseCode',
        ),
    ]
