# Generated by Django 4.1 on 2022-12-31 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Pass',
            new_name='password',
        ),
    ]
